// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArpdLDoxSQu-jWsjAJAY83X2WL6nKxV3I',
    appId: '1:62798148032:web:4a8ddbc5c5445fba3f5825',
    messagingSenderId: '62798148032',
    projectId: 'bekro-cb502',
    authDomain: 'bekro-cb502.firebaseapp.com',
    storageBucket: 'bekro-cb502.appspot.com',
    measurementId: 'G-F48RW3G3W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkYETEhgqPd5bZpEhIKbM6RbY-1oyjLYo',
    appId: '1:62798148032:android:ac62f1b0d3e78b093f5825',
    messagingSenderId: '62798148032',
    projectId: 'bekro-cb502',
    storageBucket: 'bekro-cb502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzZ42zMPu1K9HRVK-hOqBZQzi5LRXq-w',
    appId: '1:62798148032:ios:44a3f682aee8702f3f5825',
    messagingSenderId: '62798148032',
    projectId: 'bekro-cb502',
    storageBucket: 'bekro-cb502.appspot.com',
    iosClientId: '62798148032-h7mq1i7rl3022e94gp8usnh7ogi2ivp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flatChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLzZ42zMPu1K9HRVK-hOqBZQzi5LRXq-w',
    appId: '1:62798148032:ios:44a3f682aee8702f3f5825',
    messagingSenderId: '62798148032',
    projectId: 'bekro-cb502',
    storageBucket: 'bekro-cb502.appspot.com',
    iosClientId: '62798148032-h7mq1i7rl3022e94gp8usnh7ogi2ivp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flatChat',
  );
}
