// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2AMoghTUwBswTWyWMtwo7QiZZrBPQ5D0',
    appId: '1:331080468510:web:ba9af517e9f15fc36cc60f',
    messagingSenderId: '331080468510',
    projectId: 'bekron-app',
    authDomain: 'bekron-app.firebaseapp.com',
    databaseURL: 'https://bekron-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bekron-app.appspot.com',
    measurementId: 'G-LGETFHF4E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIxHkqTJysHlOSYTeBRwRYpxwiZJLxBM',
    appId: '1:331080468510:android:31d8bdc512b3ee126cc60f',
    messagingSenderId: '331080468510',
    projectId: 'bekron-app',
    databaseURL: 'https://bekron-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bekron-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARX1ps0nOuemgDEEngcCs5Ev0giKYu0qM',
    appId: '1:331080468510:ios:3cee95bed54068ed6cc60f',
    messagingSenderId: '331080468510',
    projectId: 'bekron-app',
    databaseURL: 'https://bekron-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bekron-app.appspot.com',
    iosClientId: '331080468510-8hd3oktr3abj427srte9c80442s7iq30.apps.googleusercontent.com',
    iosBundleId: 'com.example.bekronApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARX1ps0nOuemgDEEngcCs5Ev0giKYu0qM',
    appId: '1:331080468510:ios:3cee95bed54068ed6cc60f',
    messagingSenderId: '331080468510',
    projectId: 'bekron-app',
    databaseURL: 'https://bekron-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bekron-app.appspot.com',
    iosClientId: '331080468510-8hd3oktr3abj427srte9c80442s7iq30.apps.googleusercontent.com',
    iosBundleId: 'com.example.bekronApp',
  );
}
